// All antd theme variables: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
const config = require("./index");
module.exports = {
  // '@layout-body-background': `${config.backgroundColor}`,
  // '@background-color-base': '#262626',
  // '@body-background': `${config.backgroundColor}`,
  // '@layout-sider-background': `${config.backgroundColor}`,
  // '@component-background': `${config.backgroundColor}`,
  // '@layout-header-background': `${config.backgroundColor}`,
  // '@menu-dark-submenu-bg': `${config.backgroundColor}`,
  // '@input-bg': '#313133',
  // '@btn-default-bg': '#262626',
  // '@border-color-base': 'rgba(255, 255, 255, 0.25)',
  // '@border-color-split': '#363636',
  // '@heading-color': `fade(${config.primaryText}, 11%)`,
  // '@text-color-dark': `fade(${config.primaryText}, 11%)`,
  // '@text-color-secondary-dark': `fade(${config.primaryText}, 65%)`,
  // '@table-selected-row-bg': '#3a3a3a',
  // '@table-expanded-row-bg': '#3b3b3b',
  // '@table-header-bg': '#3a3a3b',
  // '@table-row-hover-bg': '#3a3a3b',
  // '@text-color': `${config.lightGrey}`,
  // '@text-color-secondary': `darken(${config.lightGrey}, 20%)`,
  // '@text-selection-bg': `${config.lightGreen}`,
  // '@layout-trigger-color': `fade(${config.primaryText}, 80%)`,
  // '@layout-trigger-background': `${config.backgroundColor}`,
  // '@alert-message-color': 'fade(#000, 67%)',
  // '@disabled-color': 'rgba(255, 255, 255, 0.25)',
  // '@tag-default-bg': '#262628',
  // '@popover-bg': '#262629',
  // '@wait-icon-color': `fade(${config.primaryText}, 64%)`,
  // '@collapse-header-bg': '#262629',
  // '@info-color': '#313133',
  // '@primary-color': `${config.lightGrey}`
};
